environment:
  matrix:
    - nodejs_version: '12.5.0'
    - nodejs_version: '12.5.0'

cache:
  - "%LOCALAPPDATA%/Yarn"
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script:
  - node --version
  - yarn --version
  - yarn run lint
  - yarn test
  - yarn run build

build: off
